BEGIN;

DO $$
DECLARE
    id_type text;
BEGIN
    SELECT data_type
      INTO id_type
      FROM information_schema.columns
     WHERE table_schema = 'public'
       AND table_name = 'users'
       AND column_name = 'id';

    IF id_type = 'uuid'
       AND NOT EXISTS (
           SELECT 1 FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = 'users'
              AND column_name = 'uuid_id'
       )
    THEN
        ALTER TABLE users RENAME COLUMN id TO uuid_id;
    END IF;
END $$;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS id bigint;

CREATE SEQUENCE IF NOT EXISTS users_id_backfill_seq;

UPDATE users
   SET id = nextval('users_id_backfill_seq')
 WHERE id IS NULL;

SELECT setval(
    'users_id_backfill_seq',
    GREATEST((SELECT coalesce(max(id), 0) FROM users), 1),
    true
);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
          FROM pg_constraint
         WHERE conrelid = 'users'::regclass
           AND conname = 'users_pkey'
           AND pg_get_constraintdef(oid) <> 'PRIMARY KEY (id)'
    )
    THEN
        ALTER TABLE users DROP CONSTRAINT users_pkey;
    END IF;
END $$;

ALTER TABLE users
    ALTER COLUMN id SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
          FROM pg_constraint
         WHERE conrelid = 'users'::regclass
           AND conname = 'users_pkey'
    )
    THEN
        ALTER TABLE users ADD CONSTRAINT users_pkey PRIMARY KEY (id);
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS users_uuid_id_key
    ON users (uuid_id)
    WHERE uuid_id IS NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
          FROM pg_attribute
         WHERE attrelid = 'users'::regclass
           AND attname = 'id'
           AND attidentity <> ''
    )
    THEN
        ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;

DO $$
DECLARE
    next_id bigint;
BEGIN
    SELECT GREATEST(coalesce(max(id), 0) + 1, 1) INTO next_id FROM users;
    EXECUTE format('ALTER TABLE users ALTER COLUMN id RESTART WITH %s', next_id);
END $$;

DROP VIEW IF EXISTS active_login_users;

CREATE VIEW active_login_users AS
SELECT id, username, password_hash, is_admin
FROM users
WHERE is_active = true;

ALTER TABLE user_sessions
    ADD COLUMN IF NOT EXISTS user_id bigint REFERENCES users(id) ON DELETE CASCADE;

UPDATE user_sessions s
   SET user_id = u.id
  FROM users u
 WHERE s.user_id IS NULL
   AND s.username = u.username;

ALTER TABLE conversations
    ADD COLUMN IF NOT EXISTS user_id bigint REFERENCES users(id) ON DELETE SET NULL;

UPDATE conversations c
   SET user_id = u.id
  FROM users u
 WHERE c.user_id IS NULL
   AND c.username = u.username;

ALTER TABLE assembly_plans
    ADD COLUMN IF NOT EXISTS user_id bigint REFERENCES users(id) ON DELETE SET NULL;

UPDATE assembly_plans ap
   SET user_id = u.id
  FROM users u
 WHERE ap.user_id IS NULL
   AND ap.created_by = u.username;

ALTER TABLE query_logs
    ADD COLUMN IF NOT EXISTS user_id bigint REFERENCES users(id) ON DELETE SET NULL;

UPDATE query_logs q
   SET user_id = u.id
  FROM users u
 WHERE q.user_id IS NULL
   AND q.username = u.username;

CREATE INDEX IF NOT EXISTS user_sessions_user_id_idx
    ON user_sessions (user_id);

CREATE INDEX IF NOT EXISTS conversations_user_id_updated_idx
    ON conversations (user_id, updated_at DESC)
    WHERE archived_at IS NULL;

CREATE INDEX IF NOT EXISTS assembly_plans_user_id_updated_idx
    ON assembly_plans (user_id, updated_at DESC);

CREATE INDEX IF NOT EXISTS query_logs_user_id_asked_idx
    ON query_logs (user_id, asked_at DESC);

CREATE TABLE IF NOT EXISTS user_preferences (
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    preference_key text NOT NULL,
    preference_value jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, preference_key)
);

CREATE INDEX IF NOT EXISTS user_preferences_user_idx
    ON user_preferences (user_id);

INSERT INTO schema_migrations (version, name)
VALUES (16, 'user_preferences')
ON CONFLICT (version) DO NOTHING;

COMMIT;
