BEGIN;

CREATE TABLE IF NOT EXISTS document_statuses (
    id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code text NOT NULL UNIQUE,
    label text NOT NULL,
    is_terminal boolean NOT NULL DEFAULT false
);

INSERT INTO document_statuses (id, code, label, is_terminal)
VALUES
    (1, 'pending', 'Pending ingest', false),
    (2, 'needs_review', 'Needs review', false),
    (3, 'indexed', 'Indexed', true),
    (4, 'failed', 'Failed', true),
    (5, 'removed', 'Removed', true)
ON CONFLICT (id) DO UPDATE
SET code = EXCLUDED.code,
    label = EXCLUDED.label,
    is_terminal = EXCLUDED.is_terminal;

SELECT setval(
    pg_get_serial_sequence('document_statuses', 'id'),
    (SELECT max(id) FROM document_statuses)
);

ALTER TABLE documents
    ADD COLUMN IF NOT EXISTS status_id smallint REFERENCES document_statuses(id);

UPDATE documents d
SET status_id = ds.id
FROM document_statuses ds
WHERE d.status_id IS NULL
  AND ds.code = d.status;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM documents WHERE status_id IS NULL) THEN
        RAISE EXCEPTION 'Cannot migrate documents.status to status_id; unknown status values exist.';
    END IF;
END $$;

ALTER TABLE documents
    ALTER COLUMN status_id SET DEFAULT 1,
    ALTER COLUMN status_id SET NOT NULL;

ALTER TABLE documents
    DROP CONSTRAINT IF EXISTS documents_status_check;

DROP INDEX IF EXISTS documents_status_idx;
CREATE INDEX IF NOT EXISTS documents_status_id_idx
    ON documents (status_id);

ALTER TABLE documents
    DROP COLUMN IF EXISTS status;

INSERT INTO schema_migrations (version, name)
VALUES (56, 'document_status_lookup_ids')
ON CONFLICT (version) DO NOTHING;

COMMIT;
