BEGIN;

CREATE TABLE IF NOT EXISTS local_gpu_work_statuses (
    id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code text NOT NULL UNIQUE,
    label text NOT NULL,
    is_terminal boolean NOT NULL DEFAULT false
);

INSERT INTO local_gpu_work_statuses (id, code, label, is_terminal)
VALUES
    (1, 'queued', 'Queued', false),
    (2, 'running', 'Running', false),
    (3, 'completed', 'Completed', true),
    (4, 'failed', 'Failed', true),
    (5, 'timed_out', 'Timed out', true),
    (6, 'cancelled', 'Cancelled', true)
ON CONFLICT (id) DO UPDATE
SET code = EXCLUDED.code,
    label = EXCLUDED.label,
    is_terminal = EXCLUDED.is_terminal;

SELECT setval(
    pg_get_serial_sequence('local_gpu_work_statuses', 'id'),
    (SELECT max(id) FROM local_gpu_work_statuses)
);

ALTER TABLE local_gpu_work_items
    ADD COLUMN IF NOT EXISTS status_id smallint REFERENCES local_gpu_work_statuses(id);

UPDATE local_gpu_work_items work
SET status_id = statuses.id
FROM local_gpu_work_statuses statuses
WHERE work.status_id IS NULL
  AND statuses.code = work.status;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM local_gpu_work_items WHERE status_id IS NULL) THEN
        RAISE EXCEPTION 'Cannot migrate local_gpu_work_items.status to status_id; unknown status values exist.';
    END IF;
END $$;

ALTER TABLE local_gpu_work_items
    ALTER COLUMN status_id SET DEFAULT 1,
    ALTER COLUMN status_id SET NOT NULL;

ALTER TABLE local_gpu_work_items
    DROP CONSTRAINT IF EXISTS local_gpu_work_items_status_check;

DROP INDEX IF EXISTS idx_local_gpu_work_items_queue;
DROP INDEX IF EXISTS idx_local_gpu_work_items_running;

CREATE INDEX IF NOT EXISTS idx_local_gpu_work_items_queue
    ON local_gpu_work_items (resource_class, status_id, priority, id)
    WHERE status_id = 1;

CREATE INDEX IF NOT EXISTS idx_local_gpu_work_items_running
    ON local_gpu_work_items (status_id, updated_at)
    WHERE status_id = 2;

ALTER TABLE local_gpu_work_items
    DROP COLUMN IF EXISTS status;

INSERT INTO schema_migrations (version, name)
VALUES (57, 'local_gpu_work_status_lookup_ids')
ON CONFLICT (version) DO NOTHING;

COMMIT;
