BEGIN;

CREATE TABLE IF NOT EXISTS assembly_plan_statuses (
    id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code text NOT NULL UNIQUE,
    label text NOT NULL,
    is_terminal boolean NOT NULL DEFAULT false
);

INSERT INTO assembly_plan_statuses (id, code, label, is_terminal)
VALUES
    (1, 'active', 'Active', false),
    (2, 'completed', 'Completed', true),
    (3, 'archived', 'Archived', true)
ON CONFLICT (id) DO UPDATE
SET code = EXCLUDED.code,
    label = EXCLUDED.label,
    is_terminal = EXCLUDED.is_terminal;

SELECT setval(
    pg_get_serial_sequence('assembly_plan_statuses', 'id'),
    (SELECT max(id) FROM assembly_plan_statuses)
);

ALTER TABLE assembly_plans
    ADD COLUMN IF NOT EXISTS status_id smallint REFERENCES assembly_plan_statuses(id);

UPDATE assembly_plans plans
SET status_id = statuses.id
FROM assembly_plan_statuses statuses
WHERE plans.status_id IS NULL
  AND statuses.code = plans.status;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM assembly_plans WHERE status_id IS NULL) THEN
        RAISE EXCEPTION 'Cannot migrate assembly_plans.status to status_id; unknown status values exist.';
    END IF;
END $$;

ALTER TABLE assembly_plans
    ALTER COLUMN status_id SET DEFAULT 1,
    ALTER COLUMN status_id SET NOT NULL;

ALTER TABLE assembly_plans
    DROP CONSTRAINT IF EXISTS assembly_plans_status_check;

ALTER TABLE assembly_plans
    DROP COLUMN IF EXISTS status;

CREATE TABLE IF NOT EXISTS performance_work_statuses (
    id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code text NOT NULL UNIQUE,
    label text NOT NULL,
    is_terminal boolean NOT NULL DEFAULT true
);

INSERT INTO performance_work_statuses (id, code, label, is_terminal)
VALUES
    (1, 'completed', 'Completed', true),
    (2, 'skipped', 'Skipped', true),
    (3, 'failed', 'Failed', true),
    (4, 'cancelled', 'Cancelled', true)
ON CONFLICT (id) DO UPDATE
SET code = EXCLUDED.code,
    label = EXCLUDED.label,
    is_terminal = EXCLUDED.is_terminal;

SELECT setval(
    pg_get_serial_sequence('performance_work_statuses', 'id'),
    (SELECT max(id) FROM performance_work_statuses)
);

ALTER TABLE performance_work_runs
    ADD COLUMN IF NOT EXISTS status_id smallint REFERENCES performance_work_statuses(id);

UPDATE performance_work_runs runs
SET status_id = statuses.id
FROM performance_work_statuses statuses
WHERE runs.status_id IS NULL
  AND statuses.code = runs.status;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM performance_work_runs WHERE status_id IS NULL) THEN
        RAISE EXCEPTION 'Cannot migrate performance_work_runs.status to status_id; unknown status values exist.';
    END IF;
END $$;

ALTER TABLE performance_work_runs
    ALTER COLUMN status_id SET DEFAULT 1,
    ALTER COLUMN status_id SET NOT NULL;

CREATE INDEX IF NOT EXISTS performance_work_runs_status_time_idx
    ON performance_work_runs (status_id, started_at DESC);

ALTER TABLE performance_work_runs
    DROP COLUMN IF EXISTS status;

INSERT INTO schema_migrations (version, name)
VALUES (58, 'plan_and_performance_status_lookup_ids')
ON CONFLICT (version) DO NOTHING;

COMMIT;
