BEGIN;

DELETE FROM app_settings
WHERE key IN (
    'APP_HOST',
    'APP_PORT',
    'BUILD_INDEX_LOG_FILE',
    'DB_MIGRATIONS_DIR',
    'DB_SCHEMA_VERSION_TABLE',
    'DOC_EXT',
    'IMG_EXTENSIONS',
    'MD_EXT',
    'PDF_EXT',
    'PDF_RENDER_MAX_PAGES_PER_DOC',
    'PADDLEOCR_PYTHON',
    'PROMPT_DIR',
    'REACT_DIST_DIR',
    'SERVER_PID_FILE',
    'TRACE_BACKUP_COUNT',
    'TRACE_LOG_FILE',
    'TRACE_LOG_LEVEL',
    'TRACE_MAX_BYTES',
    'TRACE_ROTATE',
    'TRACE_TIMESTAMPED_NAME',
    'TRACE_WHEN',
    'TESSERACT_CMD',
    'VECTOR_EMBEDDING_DIM',
    'USE_ADAPTIVE_CHUNKING',
    'ENABLE_MATH_HEAVY_CHUNKING',
    'ENABLE_TOKEN_NORMALIZATION',
    'CHUNKING_MODE',
    'CHUNK_SIZE',
    'CHUNK_OVERLAP',
    'MIN_TOKENS_PER_CHUNK',
    'MAX_TOKENS_PER_CHUNK',
    'MIN_CHUNK_QUALITY',
    'MIN_ACCEPTED_SCORE',
    'RERANK_FALLBACK_TOP_K'
);

INSERT INTO schema_migrations (version, name)
VALUES (62, 'remove_obsolete_ingestion_knobs')
ON CONFLICT (version) DO NOTHING;

COMMIT;
