INSERT INTO performance_resource_samples (
    sampled_at,
    cpu_percent,
    cpu_temperature_c,
    cpu_power_w,
    process_cpu_percent,
    process_memory_bytes,
    process_threads,
    system_memory_used_percent,
    gpu_percent,
    gpu_memory_used_percent,
    gpu_memory_used_mib,
    gpu_memory_total_mib,
    gpu_temperature_c,
    gpu_power_w,
    active_document_workers,
    active_document_worker_capacity,
    embedding_batch_active,
    reranker_batch_active,
    chunks,
    sources,
    image_ids,
    gpu_queue_active,
    gpu_queue_queued,
    gpu_queue_cuda_queued,
    gpu_queue_ocr_queued,
    gpu_queue_llm_queued,
    gpu_queue_current_wait_seconds,
    gpu_queue_recent_avg_wait_seconds,
    gpu_queue_recent_max_wait_seconds
)
VALUES (
    now(),
    %s, %s, %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s, %s, %s, %s
);
